const initialEmployees = [
  {
    id: 1,
    name: "Phan Bình An",
    email: "anpb@gmail.com",
    phone: "0985674321",
    position: "Nhân viên",
    gender: "Nam",
  },
  {
    id: 2,
    name: "Ngô Hạnh Nhi",
    email: "nhinh@gmail.com",
    phone: "0353674231",
    position: "Nhân viên",
    gender: "Nữ",
  },
  {
    id: 3,
    name: "Châu Hải Phong",
    email: "phongch@gmail.com",
    phone: "0347658833",
    position: "Quản lý",
    gender: "Nam",
  },
  {
    id: 4,
    name: "Phan Viết Lâm",
    email: "lamphan@gmail.com",
    phone: "0975444768",
    position: "Nhân viên",
    gender: "Nam",
  },
  {
    id: 5,
    name: "Lê Kim Long",
    email: "longle@gmail.com",
    phone: "0789568223",
    position: "Giám đốc",
    gender: "Nam",
  },
];
